# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Test and Deploy

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          # set VERSION as YYYY.MM.DDHHmm
          VERSION="$(echo $(date +'%Y.%m.%d%H%M'))"
          echo "::set-output name=version::$VERSION"
          echo $VERSION
      - name: echo version
        run: echo ${{ steps.properties.outputs.version }}

  draft-release-lite:
    name: Draft release for the Lite version
    # don't run on pull requests to avoid creating draft releases for pull requests
    # only run on the main branch, to avoid cutting releases from feature branches
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/refactor-github-actions' }}
    needs: [build] # TODO: needs staging-lite-test
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          submodules: true   # not used yet, but soon
      # Remove old release drafts by using the curl request for the available releases with draft flag
      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
            | tr '\r\n' ' ' \
            | jq '.[] | select(.draft == true) | .id' \
            | xargs -I '{}' \
          curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/{}

      # Create new release draft - which is not publicly visible and requires manual acceptance
      - name: Create Release Draft
        id: createDraft
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build.outputs.version }}
          release_name: v${{ needs.build.outputs.version }}
          body: 'This is a draft release for the Lite version of the plugin.'
          draft: true

