# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Test and Deploy

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn test:unit

  staging-lite-hosting:
    needs: build
    name: Deploy to staging lite hosting
    environment:
      name: staging-lite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      # It was failing when we change the following to lines to use npm run
      - run: yarn deploy:lite:stage:hosting --token ${{ secrets.FIREBASE_TOKEN }}

  staging-lite-functions:
    needs: build
    name: Deploy to staging lite functions
    environment:
      name: staging-lite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      # It was failing when we change the following to lines to use npm run
      - run: yarn deploy:lite:stage:functions --token ${{ secrets.FIREBASE_TOKEN }}

  staging-full:
    needs: build
    name: Deploy to staging full
    environment:
      name: staging-full
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      # It was failing when we change the following to lines to use npm run
      - run: yarn deploy:full:stage --token ${{ secrets.FIREBASE_TOKEN }}

  prod-lite:
    needs: [staging-lite-hosting, staging-lite-functions]
    name: Deploy to production lite
    environment:
      name: prod-lite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      # It was failing when we change the following to lines to use npm run
      - run: yarn deploy:lite:prod --token ${{ secrets.FIREBASE_TOKEN }}
      - name: Bump version and push tag1
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v-lite-

  prod-full:
    needs: staging-full
    name: Deploy to production full
    environment:
      name: prod-full
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      # It was failing when we change the following to lines to use npm run
      - run: yarn deploy:full:prod --token ${{ secrets.FIREBASE_TOKEN }}
      - name: Bump version and push tag1
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v-full-
