# GitHub Actions Workflow created for handling the release process based on the draft release prepared
# with the Build workflow. Running the publishPlugin task requires the PUBLISH_TOKEN secret provided.

name: Release
on:
  release:
    types: [prereleased, released]

jobs:
  release:
    name: Deploy to staging
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Set environment variables
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          # extract License from github.event.release.tag_name
          LICENSE=$(echo ${{ github.event.release.tag_name }} | cut -d'-' -f2)
          echo "::set-output name=license::$LICENSE"
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: yarn install
        shell: bash
        run: yarn install
      - name: yarn build
        shell: bash
        run: yarn build:${{ steps.properties.outputs.license }}
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ inputs.cloudflare-api-token }}
          accountId: ${{ inputs.cloudflare-account-id }}
          command: pages publish dist --branch production --project-name=conf-stg-${{ steps.properties.outputs.license }}


